#!/bin/bash
allThreads=("package.json" ".babelrc" "0-redis_client.js" "1-redis_op.js" "2-redis_op_async.js" "4-redis_advanced_op.js" "5-subscriber.js" "5-publisher.js" "6-job_creator.js" "6-job_processor.js" "7-job_creator.js" "7-job_processor.js" "8-job.js" "8-job.test.js" "9-stock.js" "100-seat.js")

mkdir -p "0x03-queuing_system_in_js"

for t in ${allThreads[@]}; do

    if [[ $t == *".py"* ]]; then
        echo -e "#!/usr/bin/env python3\n" > "./0x03-queuing_system_in_js/$t" && chmod +x "./0x03-queuing_system_in_js/$t"
    else
        # echo -e "#!/usr/bin/node\n" > "./0x03-queuing_system_in_js/$t"
        touch "./0x03-queuing_system_in_js/$t"
    fi
done

echo -e "# ALX Programme Project: 0x03. Queuing System in JS
" > "./0x03-queuing_system_in_js/README.md"

echo -e "#!/bin/bash\ngit add . && git commit -m '0x03. Queuing System in JS
' && git push"  > "./0x03-queuing_system_in_js/correction" && chmod +x "./0x03-queuing_system_in_js/correction"

cp "../alx-higher_level_programming/0x05-python-exceptions/clean_up_corrections" "./0x03-queuing_system_in_js/"

cd ./0x03-queuing_system_in_js
